#ifndef _OPCODE_HPP_
#define _OPCODE_HPP_

enum Opcode {
	HALT, GOTO, JMP, JE, JNE, JGT, JLT, JGET, JLET,
	BAND, BOR, BXOR, BSL1, BSR1, BSL, BSR,
	ADD, SUB, MUL, DIV, MOD,
		
	LOADUI8, LOADUI16, LOADUI32, LOADUI,
	LOADI8, LOADI16, LOADI32, LOADI,
	LOADF, LOADD, LOADA, 
	LOADV_CONST, LOADA_CONST, LOADSP_CONST,
		
	STOREUI8, STOREUI16, STOREUI32, STOREUI,
	STOREI8, STOREI16, STOREI32, STOREI,
	STOREF, STORED, STOREA,
		
	PUSHB_CONST, POPB_CONST, PUSHB, POPB
};

char const* OPCODE_NAMES[] = {
    "HALT", "GOTO", "JMP", "JE", "JNE", "JGT", "JLT", "JGET", "JLET",
	"BAND", "BOR", "BXOR", "BSL1", "BSR1", "BSL", "BSR",
	"ADD", "SUB", "MUL", "DIV", "MOD",
	
	"LOADUI8", "LOADUI16", "LOADUI32", "LOADUI",
	"LOADI8", "LOADI16", "LOADI32", "LOADI",
	"LOADF", "LOADD", "LOADA",
	"LOADV_CONST", "LOADA_CONST", "LOADSP_CONST",
	
	"STOREUI8", "STOREUI16", "STOREUI32", "STOREUI",
	"STOREI8", "STOREI16", "STOREI32", "STOREI",
	"STOREF", "STORED", "STOREA",
	
	"PUSHB_CONST", "POPB_CONST", "PUSHB", "POPB"
};

#endif